# -*- coding: utf-8 -*-
"""Single Layer Perceptron .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wa-dr6UMSQ9XqepHsY--3P2WkqZYgh1p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.plotting import plot_decision_regions
from sklearn.model_selection import train_test_split

df=pd.read_csv('/content/placement (1).csv')
df.head()

df.rename(columns={'placement_exam_marks': 'score'}, inplace=True)

df.head()

"""# **plot data**"""

plt.figure(figsize=(6,4))
sns.scatterplot(x='cgpa',y='score',data=df,hue="placed")
plt.show()

x=df.iloc[:,:-1]
y=df.iloc[:,-1]

print(x)

print(y)

"""# **Data split**"""

# from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

"""# **Model**"""

from sklearn.linear_model import Perceptron

pr=Perceptron()

pr.fit(x_train,y_train)

"""# **Accuracy**"""

pr.score(x_train,y_train)*100

pr.score(x_test,y_test)*100

plot_decision_regions(x.to_numpy(),y.to_numpy(),clf=pr)

plt.show()

