# -*- coding: utf-8 -*-
"""mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQtKxjdzapXIKnryhILVZMzvbeoXcZja
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from tensorflow import keras

(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

print(len(x_train))
print(len(x_test))

x_train[0].shape

x_train[0]

plt.matshow(x_train[0])

y_train[:5]

x_train.shape

#scaling
x_train=x_train/225
x_test=x_test/225

x_train_flattend=x_train.reshape(len(x_train),28*28)
x_test_flattend=x_test.reshape(len(x_test),28*28)

x_train_flattend.shape

x_train_flattend[0]

model=keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_flattend,y_train,epochs=5)

model.evaluate(x_test_flattend,y_test)

plt.matshow(x_test[9])

y_predected=model.predict(x_test_flattend)
y_predected[9]

np.argmax(y_predected[9])

model=keras.Sequential([
    keras.layers.Dense(100,input_shape=(784,),activation='relu'),    #add hidden layer
     keras.layers.Dense(10,activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_flattend,y_train,epochs=5)

model.evaluate(x_test_flattend,y_test)

model=keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100,activation='relu'),    #add hidden layer
     keras.layers.Dense(10,activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train,y_train,epochs=5)

