# -*- coding: utf-8 -*-
"""DL Project 3. Dog vs Cat Classification - Transfer Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mb4vhAySlviZQwzsYzgZA435qqMbxbEs
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df=pd.read_csv('/content/insurance_data.csv')
df

df.shape

x=df.drop('bought_insurance',axis=1)
y=df['bought_insurance']

x_train,x_test,y_train,_y_test=train_test_split(x,y,test_size=0.2,random_state=25)

model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',)
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train,y_train,epochs=5)

